kind: pipeline
name: Docker

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: hackherz/padwoman
    auto_tag: true
    username: hackherz
    password:
      from_secret: docker_pw

---
kind: pipeline
name: Documentation

trigger:
  branch:
    - releases

steps:
  - name: Build
    image: python:3.7
    commands:
      - pip install mkdocs mkdocs-material
      - mkdocs build

  - name: Upload
    image: plugins/s3
    settings:
      bucket: hackherz-website
      access_key:
        from_secret: access_key
      secret_key:
        from_secret: secret_key
      source: site/**/*
      target: /padwoman/
      strip_prefix: site/
      path_style: true
      endpoint: https://s3.fckggl.de
